name: Windows Installers Creation and Publication

on: [push]

jobs:
    create-windows-installers:
        runs-on: windows-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Build Windows Installers 
            run: .\build.bat
            shell: cmd

          - name: Upload installers as artifacts
            uses: actions/upload-artifact@v2
            with:
                name: fzf-win installers
                path: build/**/*.msi

          - name: Upload MSI for Windows to release page
            if: github.ref == 'refs/heads/main'
            uses: "marvinpinto/action-automatic-releases@latest"
            with:
                repo_token: "${{ secrets.ACTIONS_TOKEN }}"
                automatic_release_tag: "test"
                prerelease: true
                title: "Windows Development Build"
                files: |
                    fzf-win-installer.msi
